// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.29.0
// source: proto/tmux.proto

package tmuxproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaneRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host    string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"` // ssh alias or empty for local
	Session string `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Window  string `protobuf:"bytes,3,opt,name=window,proto3" json:"window,omitempty"`
	Pane    string `protobuf:"bytes,4,opt,name=pane,proto3" json:"pane,omitempty"` // tmux pane id (optional if default)
}

func (x *PaneRef) Reset() {
	*x = PaneRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmux_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaneRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaneRef) ProtoMessage() {}

func (x *PaneRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmux_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaneRef.ProtoReflect.Descriptor instead.
func (*PaneRef) Descriptor() ([]byte, []int) {
	return file_proto_tmux_proto_rawDescGZIP(), []int{0}
}

func (x *PaneRef) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PaneRef) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *PaneRef) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

func (x *PaneRef) GetPane() string {
	if x != nil {
		return x.Pane
	}
	return ""
}

type StreamPaneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target        *PaneRef `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	FromSeq       uint64   `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	StripAnsi     bool     `protobuf:"varint,3,opt,name=strip_ansi,json=stripAnsi,proto3" json:"strip_ansi,omitempty"`
	MaxChunkBytes uint32   `protobuf:"varint,4,opt,name=max_chunk_bytes,json=maxChunkBytes,proto3" json:"max_chunk_bytes,omitempty"`
}

func (x *StreamPaneRequest) Reset() {
	*x = StreamPaneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmux_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamPaneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPaneRequest) ProtoMessage() {}

func (x *StreamPaneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmux_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPaneRequest.ProtoReflect.Descriptor instead.
func (*StreamPaneRequest) Descriptor() ([]byte, []int) {
	return file_proto_tmux_proto_rawDescGZIP(), []int{1}
}

func (x *StreamPaneRequest) GetTarget() *PaneRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *StreamPaneRequest) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

func (x *StreamPaneRequest) GetStripAnsi() bool {
	if x != nil {
		return x.StripAnsi
	}
	return false
}

func (x *StreamPaneRequest) GetMaxChunkBytes() uint32 {
	if x != nil {
		return x.MaxChunkBytes
	}
	return 0
}

type PaneChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target       *PaneRef `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Seq          uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	TsUnixMillis int64    `protobuf:"varint,3,opt,name=ts_unix_millis,json=tsUnixMillis,proto3" json:"ts_unix_millis,omitempty"`
	Data         []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	IsTruncated  bool     `protobuf:"varint,5,opt,name=is_truncated,json=isTruncated,proto3" json:"is_truncated,omitempty"`
	Heartbeat    bool     `protobuf:"varint,6,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Eof          bool     `protobuf:"varint,7,opt,name=eof,proto3" json:"eof,omitempty"`
	Reason       string   `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *PaneChunk) Reset() {
	*x = PaneChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmux_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaneChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaneChunk) ProtoMessage() {}

func (x *PaneChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmux_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaneChunk.ProtoReflect.Descriptor instead.
func (*PaneChunk) Descriptor() ([]byte, []int) {
	return file_proto_tmux_proto_rawDescGZIP(), []int{2}
}

func (x *PaneChunk) GetTarget() *PaneRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *PaneChunk) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PaneChunk) GetTsUnixMillis() int64 {
	if x != nil {
		return x.TsUnixMillis
	}
	return 0
}

func (x *PaneChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PaneChunk) GetIsTruncated() bool {
	if x != nil {
		return x.IsTruncated
	}
	return false
}

func (x *PaneChunk) GetHeartbeat() bool {
	if x != nil {
		return x.Heartbeat
	}
	return false
}

func (x *PaneChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

func (x *PaneChunk) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SnapshotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target       *PaneRef `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	CaptureLines uint32   `protobuf:"varint,2,opt,name=capture_lines,json=captureLines,proto3" json:"capture_lines,omitempty"`
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmux_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmux_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_tmux_proto_rawDescGZIP(), []int{3}
}

func (x *SnapshotRequest) GetTarget() *PaneRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *SnapshotRequest) GetCaptureLines() uint32 {
	if x != nil {
		return x.CaptureLines
	}
	return 0
}

type SnapshotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sessions string `protobuf:"bytes,1,opt,name=sessions,proto3" json:"sessions,omitempty"`
	Windows  string `protobuf:"bytes,2,opt,name=windows,proto3" json:"windows,omitempty"`
	Panes    string `protobuf:"bytes,3,opt,name=panes,proto3" json:"panes,omitempty"`
	Capture  string `protobuf:"bytes,4,opt,name=capture,proto3" json:"capture,omitempty"`
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmux_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmux_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_tmux_proto_rawDescGZIP(), []int{4}
}

func (x *SnapshotResponse) GetSessions() string {
	if x != nil {
		return x.Sessions
	}
	return ""
}

func (x *SnapshotResponse) GetWindows() string {
	if x != nil {
		return x.Windows
	}
	return ""
}

func (x *SnapshotResponse) GetPanes() string {
	if x != nil {
		return x.Panes
	}
	return ""
}

func (x *SnapshotResponse) GetCapture() string {
	if x != nil {
		return x.Capture
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target *PaneRef `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmux_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmux_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_tmux_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequest) GetTarget() *PaneRef {
	if x != nil {
		return x.Target
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmux_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmux_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_tmux_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SetDefaultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target *PaneRef `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *SetDefaultRequest) Reset() {
	*x = SetDefaultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmux_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDefaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultRequest) ProtoMessage() {}

func (x *SetDefaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmux_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultRequest.ProtoReflect.Descriptor instead.
func (*SetDefaultRequest) Descriptor() ([]byte, []int) {
	return file_proto_tmux_proto_rawDescGZIP(), []int{7}
}

func (x *SetDefaultRequest) GetTarget() *PaneRef {
	if x != nil {
		return x.Target
	}
	return nil
}

type SetDefaultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *SetDefaultResponse) Reset() {
	*x = SetDefaultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmux_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDefaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultResponse) ProtoMessage() {}

func (x *SetDefaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmux_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultResponse.ProtoReflect.Descriptor instead.
func (*SetDefaultResponse) Descriptor() ([]byte, []int) {
	return file_proto_tmux_proto_rawDescGZIP(), []int{8}
}

func (x *SetDefaultResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CapturePaneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target    *PaneRef `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Lines     int32    `protobuf:"varint,2,opt,name=lines,proto3" json:"lines,omitempty"` // negative or zero -> default tail
	StripAnsi bool     `protobuf:"varint,3,opt,name=strip_ansi,json=stripAnsi,proto3" json:"strip_ansi,omitempty"`
}

func (x *CapturePaneRequest) Reset() {
	*x = CapturePaneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmux_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CapturePaneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapturePaneRequest) ProtoMessage() {}

func (x *CapturePaneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmux_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapturePaneRequest.ProtoReflect.Descriptor instead.
func (*CapturePaneRequest) Descriptor() ([]byte, []int) {
	return file_proto_tmux_proto_rawDescGZIP(), []int{9}
}

func (x *CapturePaneRequest) GetTarget() *PaneRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *CapturePaneRequest) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

func (x *CapturePaneRequest) GetStripAnsi() bool {
	if x != nil {
		return x.StripAnsi
	}
	return false
}

type CapturePaneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text      string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Truncated bool   `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"`
}

func (x *CapturePaneResponse) Reset() {
	*x = CapturePaneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmux_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CapturePaneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapturePaneResponse) ProtoMessage() {}

func (x *CapturePaneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmux_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapturePaneResponse.ProtoReflect.Descriptor instead.
func (*CapturePaneResponse) Descriptor() ([]byte, []int) {
	return file_proto_tmux_proto_rawDescGZIP(), []int{10}
}

func (x *CapturePaneResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CapturePaneResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type RunCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target    *PaneRef `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Args      []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	StripAnsi bool     `protobuf:"varint,3,opt,name=strip_ansi,json=stripAnsi,proto3" json:"strip_ansi,omitempty"`
}

func (x *RunCommandRequest) Reset() {
	*x = RunCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmux_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandRequest) ProtoMessage() {}

func (x *RunCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmux_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandRequest.ProtoReflect.Descriptor instead.
func (*RunCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_tmux_proto_rawDescGZIP(), []int{11}
}

func (x *RunCommandRequest) GetTarget() *PaneRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *RunCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunCommandRequest) GetStripAnsi() bool {
	if x != nil {
		return x.StripAnsi
	}
	return false
}

type RunCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *RunCommandResponse) Reset() {
	*x = RunCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmux_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandResponse) ProtoMessage() {}

func (x *RunCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmux_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandResponse.ProtoReflect.Descriptor instead.
func (*RunCommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_tmux_proto_rawDescGZIP(), []int{12}
}

func (x *RunCommandResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendKeysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target *PaneRef `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Keys   []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Enter  bool     `protobuf:"varint,3,opt,name=enter,proto3" json:"enter,omitempty"`
}

func (x *SendKeysRequest) Reset() {
	*x = SendKeysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmux_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKeysRequest) ProtoMessage() {}

func (x *SendKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmux_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKeysRequest.ProtoReflect.Descriptor instead.
func (*SendKeysRequest) Descriptor() ([]byte, []int) {
	return file_proto_tmux_proto_rawDescGZIP(), []int{13}
}

func (x *SendKeysRequest) GetTarget() *PaneRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *SendKeysRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *SendKeysRequest) GetEnter() bool {
	if x != nil {
		return x.Enter
	}
	return false
}

type SendKeysResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *SendKeysResponse) Reset() {
	*x = SendKeysResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmux_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKeysResponse) ProtoMessage() {}

func (x *SendKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmux_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKeysResponse.ProtoReflect.Descriptor instead.
func (*SendKeysResponse) Descriptor() ([]byte, []int) {
	return file_proto_tmux_proto_rawDescGZIP(), []int{14}
}

func (x *SendKeysResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type RunBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target       *PaneRef `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Steps        []string `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`                                 // shell fragments to join
	JoinWith     string   `protobuf:"bytes,3,opt,name=join_with,json=joinWith,proto3" json:"join_with,omitempty"`           // default "&&"
	CleanPrompt  bool     `protobuf:"varint,4,opt,name=clean_prompt,json=cleanPrompt,proto3" json:"clean_prompt,omitempty"` // send C-c/C-u before running
	StripAnsi    bool     `protobuf:"varint,5,opt,name=strip_ansi,json=stripAnsi,proto3" json:"strip_ansi,omitempty"`
	CaptureLines int32    `protobuf:"varint,6,opt,name=capture_lines,json=captureLines,proto3" json:"capture_lines,omitempty"` // optional capture after run (0 = skip)
}

func (x *RunBatchRequest) Reset() {
	*x = RunBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmux_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunBatchRequest) ProtoMessage() {}

func (x *RunBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmux_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunBatchRequest.ProtoReflect.Descriptor instead.
func (*RunBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_tmux_proto_rawDescGZIP(), []int{15}
}

func (x *RunBatchRequest) GetTarget() *PaneRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *RunBatchRequest) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *RunBatchRequest) GetJoinWith() string {
	if x != nil {
		return x.JoinWith
	}
	return ""
}

func (x *RunBatchRequest) GetCleanPrompt() bool {
	if x != nil {
		return x.CleanPrompt
	}
	return false
}

func (x *RunBatchRequest) GetStripAnsi() bool {
	if x != nil {
		return x.StripAnsi
	}
	return false
}

func (x *RunBatchRequest) GetCaptureLines() int32 {
	if x != nil {
		return x.CaptureLines
	}
	return 0
}

type RunBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text      string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`       // status message
	Capture   string `protobuf:"bytes,2,opt,name=capture,proto3" json:"capture,omitempty"` // optional capture text
	Truncated bool   `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
}

func (x *RunBatchResponse) Reset() {
	*x = RunBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tmux_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunBatchResponse) ProtoMessage() {}

func (x *RunBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tmux_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunBatchResponse.ProtoReflect.Descriptor instead.
func (*RunBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_tmux_proto_rawDescGZIP(), []int{16}
}

func (x *RunBatchResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RunBatchResponse) GetCapture() string {
	if x != nil {
		return x.Capture
	}
	return ""
}

func (x *RunBatchResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

var File_proto_tmux_proto protoreflect.FileDescriptor

var file_proto_tmux_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x22,
	0x63, 0x0a, 0x07, 0x50, 0x61, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x69, 0x6e, 0x64,
	0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x6e, 0x65, 0x22, 0xa3, 0x01, 0x0a, 0x11, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50,
	0x61, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x63, 0x70,
	0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x6e, 0x65, 0x52, 0x65, 0x66,
	0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d,
	0x5f, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d,
	0x53, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x61, 0x6e, 0x73,
	0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x74, 0x72, 0x69, 0x70, 0x41, 0x6e,
	0x73, 0x69, 0x12, 0x26, 0x0a, 0x0f, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6d, 0x61, 0x78,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0xf0, 0x01, 0x0a, 0x09, 0x50,
	0x61, 0x6e, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x2c, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x74,
	0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x52, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x73, 0x5f, 0x75,
	0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x74, 0x73, 0x55, 0x6e, 0x69, 0x78, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x74, 0x72, 0x75, 0x6e, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x54, 0x72, 0x75, 0x6e,
	0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65,
	0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6f, 0x66, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x03, 0x65, 0x6f, 0x66, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x64, 0x0a,
	0x0f, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2c, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x61, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x23,
	0x0a, 0x0d, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x69,
	0x6e, 0x65, 0x73, 0x22, 0x78, 0x0a, 0x10, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x61, 0x6e, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61,
	0x6e, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x22, 0x3b, 0x0a,
	0x0b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d,
	0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x6e, 0x65, 0x52,
	0x65, 0x66, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x22, 0x0a, 0x0c, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x41,
	0x0a, 0x11, 0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x61, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x22, 0x28, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x77, 0x0a, 0x12, 0x43,
	0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x50, 0x61, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2c, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x61, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x61,
	0x6e, 0x73, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x74, 0x72, 0x69, 0x70,
	0x41, 0x6e, 0x73, 0x69, 0x22, 0x47, 0x0a, 0x13, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x50,
	0x61, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x72, 0x75, 0x6e, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x74, 0x72, 0x75, 0x6e, 0x63, 0x61, 0x74, 0x65, 0x64, 0x22, 0x74, 0x0a,
	0x11, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x61, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x61, 0x6e,
	0x73, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x74, 0x72, 0x69, 0x70, 0x41,
	0x6e, 0x73, 0x69, 0x22, 0x28, 0x0a, 0x12, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x69, 0x0a,
	0x0f, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2c, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x61, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65,
	0x79, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x26, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64,
	0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x22, 0xd9, 0x01, 0x0a, 0x0f, 0x52, 0x75, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x61, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x6f, 0x69, 0x6e,
	0x5f, 0x77, 0x69, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6a, 0x6f, 0x69,
	0x6e, 0x57, 0x69, 0x74, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x5f, 0x70,
	0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x63, 0x6c, 0x65,
	0x61, 0x6e, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x69,
	0x70, 0x5f, 0x61, 0x6e, 0x73, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x74,
	0x72, 0x69, 0x70, 0x41, 0x6e, 0x73, 0x69, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x70, 0x74, 0x75,
	0x72, 0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x73, 0x22, 0x5e, 0x0a, 0x10,
	0x52, 0x75, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x72, 0x75, 0x6e, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x74, 0x72, 0x75, 0x6e, 0x63, 0x61, 0x74, 0x65, 0x64, 0x32, 0xeb, 0x05, 0x0a,
	0x0b, 0x54, 0x6d, 0x75, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0a,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x61, 0x6e, 0x65, 0x12, 0x1e, 0x2e, 0x6d, 0x63, 0x70,
	0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50,
	0x61, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x63, 0x70,
	0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x6e, 0x65, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x30, 0x01, 0x12, 0x47, 0x0a, 0x08, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x12, 0x1c, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a,
	0x0b, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x50, 0x61, 0x6e, 0x65, 0x12, 0x1f, 0x2e, 0x6d,
	0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x75,
	0x72, 0x65, 0x50, 0x61, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x70, 0x74,
	0x75, 0x72, 0x65, 0x50, 0x61, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4d, 0x0a, 0x0a, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1e, 0x2e,
	0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47,
	0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x1c, 0x2e, 0x6d, 0x63, 0x70,
	0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x74,
	0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x08, 0x52, 0x75, 0x6e, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x12, 0x1c, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x75, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x75, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x43, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x18, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x63, 0x70,
	0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x6e,
	0x64, 0x6f, 0x77, 0x73, 0x12, 0x18, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x61, 0x6e, 0x65, 0x73, 0x12, 0x18, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75,
	0x78, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x6d, 0x63, 0x70, 0x2e, 0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0a, 0x53,
	0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x1e, 0x2e, 0x6d, 0x63, 0x70, 0x2e,
	0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6d, 0x63, 0x70, 0x2e,
	0x74, 0x6d, 0x75, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x38, 0x69, 0x6b, 0x61, 0x30, 0x73,
	0x2f, 0x6d, 0x63, 0x70, 0x2d, 0x74, 0x6d, 0x75, 0x78, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x3b, 0x74, 0x6d, 0x75, 0x78, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_tmux_proto_rawDescOnce sync.Once
	file_proto_tmux_proto_rawDescData = file_proto_tmux_proto_rawDesc
)

func file_proto_tmux_proto_rawDescGZIP() []byte {
	file_proto_tmux_proto_rawDescOnce.Do(func() {
		file_proto_tmux_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_tmux_proto_rawDescData)
	})
	return file_proto_tmux_proto_rawDescData
}

var file_proto_tmux_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_tmux_proto_goTypes = []interface{}{
	(*PaneRef)(nil),             // 0: mcp.tmux.v1.PaneRef
	(*StreamPaneRequest)(nil),   // 1: mcp.tmux.v1.StreamPaneRequest
	(*PaneChunk)(nil),           // 2: mcp.tmux.v1.PaneChunk
	(*SnapshotRequest)(nil),     // 3: mcp.tmux.v1.SnapshotRequest
	(*SnapshotResponse)(nil),    // 4: mcp.tmux.v1.SnapshotResponse
	(*ListRequest)(nil),         // 5: mcp.tmux.v1.ListRequest
	(*ListResponse)(nil),        // 6: mcp.tmux.v1.ListResponse
	(*SetDefaultRequest)(nil),   // 7: mcp.tmux.v1.SetDefaultRequest
	(*SetDefaultResponse)(nil),  // 8: mcp.tmux.v1.SetDefaultResponse
	(*CapturePaneRequest)(nil),  // 9: mcp.tmux.v1.CapturePaneRequest
	(*CapturePaneResponse)(nil), // 10: mcp.tmux.v1.CapturePaneResponse
	(*RunCommandRequest)(nil),   // 11: mcp.tmux.v1.RunCommandRequest
	(*RunCommandResponse)(nil),  // 12: mcp.tmux.v1.RunCommandResponse
	(*SendKeysRequest)(nil),     // 13: mcp.tmux.v1.SendKeysRequest
	(*SendKeysResponse)(nil),    // 14: mcp.tmux.v1.SendKeysResponse
	(*RunBatchRequest)(nil),     // 15: mcp.tmux.v1.RunBatchRequest
	(*RunBatchResponse)(nil),    // 16: mcp.tmux.v1.RunBatchResponse
}
var file_proto_tmux_proto_depIdxs = []int32{
	0,  // 0: mcp.tmux.v1.StreamPaneRequest.target:type_name -> mcp.tmux.v1.PaneRef
	0,  // 1: mcp.tmux.v1.PaneChunk.target:type_name -> mcp.tmux.v1.PaneRef
	0,  // 2: mcp.tmux.v1.SnapshotRequest.target:type_name -> mcp.tmux.v1.PaneRef
	0,  // 3: mcp.tmux.v1.ListRequest.target:type_name -> mcp.tmux.v1.PaneRef
	0,  // 4: mcp.tmux.v1.SetDefaultRequest.target:type_name -> mcp.tmux.v1.PaneRef
	0,  // 5: mcp.tmux.v1.CapturePaneRequest.target:type_name -> mcp.tmux.v1.PaneRef
	0,  // 6: mcp.tmux.v1.RunCommandRequest.target:type_name -> mcp.tmux.v1.PaneRef
	0,  // 7: mcp.tmux.v1.SendKeysRequest.target:type_name -> mcp.tmux.v1.PaneRef
	0,  // 8: mcp.tmux.v1.RunBatchRequest.target:type_name -> mcp.tmux.v1.PaneRef
	1,  // 9: mcp.tmux.v1.TmuxService.StreamPane:input_type -> mcp.tmux.v1.StreamPaneRequest
	3,  // 10: mcp.tmux.v1.TmuxService.Snapshot:input_type -> mcp.tmux.v1.SnapshotRequest
	9,  // 11: mcp.tmux.v1.TmuxService.CapturePane:input_type -> mcp.tmux.v1.CapturePaneRequest
	11, // 12: mcp.tmux.v1.TmuxService.RunCommand:input_type -> mcp.tmux.v1.RunCommandRequest
	13, // 13: mcp.tmux.v1.TmuxService.SendKeys:input_type -> mcp.tmux.v1.SendKeysRequest
	15, // 14: mcp.tmux.v1.TmuxService.RunBatch:input_type -> mcp.tmux.v1.RunBatchRequest
	5,  // 15: mcp.tmux.v1.TmuxService.ListSessions:input_type -> mcp.tmux.v1.ListRequest
	5,  // 16: mcp.tmux.v1.TmuxService.ListWindows:input_type -> mcp.tmux.v1.ListRequest
	5,  // 17: mcp.tmux.v1.TmuxService.ListPanes:input_type -> mcp.tmux.v1.ListRequest
	7,  // 18: mcp.tmux.v1.TmuxService.SetDefault:input_type -> mcp.tmux.v1.SetDefaultRequest
	2,  // 19: mcp.tmux.v1.TmuxService.StreamPane:output_type -> mcp.tmux.v1.PaneChunk
	4,  // 20: mcp.tmux.v1.TmuxService.Snapshot:output_type -> mcp.tmux.v1.SnapshotResponse
	10, // 21: mcp.tmux.v1.TmuxService.CapturePane:output_type -> mcp.tmux.v1.CapturePaneResponse
	12, // 22: mcp.tmux.v1.TmuxService.RunCommand:output_type -> mcp.tmux.v1.RunCommandResponse
	14, // 23: mcp.tmux.v1.TmuxService.SendKeys:output_type -> mcp.tmux.v1.SendKeysResponse
	16, // 24: mcp.tmux.v1.TmuxService.RunBatch:output_type -> mcp.tmux.v1.RunBatchResponse
	6,  // 25: mcp.tmux.v1.TmuxService.ListSessions:output_type -> mcp.tmux.v1.ListResponse
	6,  // 26: mcp.tmux.v1.TmuxService.ListWindows:output_type -> mcp.tmux.v1.ListResponse
	6,  // 27: mcp.tmux.v1.TmuxService.ListPanes:output_type -> mcp.tmux.v1.ListResponse
	8,  // 28: mcp.tmux.v1.TmuxService.SetDefault:output_type -> mcp.tmux.v1.SetDefaultResponse
	19, // [19:29] is the sub-list for method output_type
	9,  // [9:19] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_tmux_proto_init() }
func file_proto_tmux_proto_init() {
	if File_proto_tmux_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_tmux_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaneRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tmux_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamPaneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tmux_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaneChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tmux_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tmux_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tmux_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tmux_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tmux_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDefaultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tmux_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDefaultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tmux_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CapturePaneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tmux_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CapturePaneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tmux_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tmux_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tmux_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendKeysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tmux_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendKeysResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tmux_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tmux_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_tmux_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tmux_proto_goTypes,
		DependencyIndexes: file_proto_tmux_proto_depIdxs,
		MessageInfos:      file_proto_tmux_proto_msgTypes,
	}.Build()
	File_proto_tmux_proto = out.File
	file_proto_tmux_proto_rawDesc = nil
	file_proto_tmux_proto_goTypes = nil
	file_proto_tmux_proto_depIdxs = nil
}
